services:
  - type: web
    name: jsonhero-web
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SESSION_SECRET
        value: "replace_me_secure"
      - key: NODE_ENV
        value: "production"
